-- ============================================================
-- Higher Education AI Platform - H2 Schema (Dev Profile)
-- H2 in PostgreSQL compatibility mode
-- ============================================================

-- 1. Authentication & RBAC
CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL UNIQUE,
    password        VARCHAR(256) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    email           VARCHAR(128),
    phone           VARCHAR(32),
    avatar          VARCHAR(512),
    status          SMALLINT     NOT NULL DEFAULT 1,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    sort_order      INT          NOT NULL DEFAULT 0,
    status          SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    role_id         BIGINT NOT NULL,
    UNIQUE(user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_org (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       BIGINT       DEFAULT 0,
    name            VARCHAR(128) NOT NULL,
    code            VARCHAR(64)  UNIQUE,
    type            VARCHAR(32)  NOT NULL DEFAULT 'department',
    sort_order      INT          NOT NULL DEFAULT 0,
    status          SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user_org (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    org_id          BIGINT NOT NULL,
    UNIQUE(user_id, org_id)
);

CREATE TABLE IF NOT EXISTS sys_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(128) NOT NULL UNIQUE,
    name            VARCHAR(256) NOT NULL,
    description     VARCHAR(512),
    sort_order      INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT NOT NULL,
    permission_id   BIGINT NOT NULL,
    UNIQUE(role_id, permission_id)
);

-- 2. Resource Center
CREATE TABLE IF NOT EXISTS res_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    parent_id       BIGINT       DEFAULT 0,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS res_file (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(512) NOT NULL,
    original_name   VARCHAR(512) NOT NULL,
    file_type       VARCHAR(32)  NOT NULL,
    file_size       BIGINT       NOT NULL DEFAULT 0,
    storage_path    VARCHAR(1024),
    category_id     BIGINT,
    parse_status    VARCHAR(32)  NOT NULL DEFAULT 'pending',
    vector_status   VARCHAR(32)  NOT NULL DEFAULT 'pending',
    markdown_path   VARCHAR(1024),
    owner_id        BIGINT       NOT NULL,
    is_public       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS res_file_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id         BIGINT  NOT NULL,
    target_type     VARCHAR(32) NOT NULL,
    target_id       BIGINT  NOT NULL,
    permission      VARCHAR(32) NOT NULL DEFAULT 'read',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS res_parse_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id         BIGINT  NOT NULL,
    task_type       VARCHAR(32) NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'pending',
    result          TEXT,
    error_message   TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Agent / Skill / MCP
CREATE TABLE IF NOT EXISTS agent_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    avatar          VARCHAR(512),
    category        VARCHAR(64),
    agent_type      VARCHAR(32) NOT NULL DEFAULT 'openclaw',
    config          TEXT,
    status          VARCHAR(32) NOT NULL DEFAULT 'draft',
    owner_id        BIGINT  NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    use_count       BIGINT  NOT NULL DEFAULT 0,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id        BIGINT NOT NULL,
    target_type     VARCHAR(32) NOT NULL,
    target_id       BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_publish (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id        BIGINT NOT NULL,
    channel_type    VARCHAR(64) NOT NULL,
    config          TEXT,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    skill_type      VARCHAR(32) NOT NULL DEFAULT 'tool',
    config          TEXT,
    owner_id        BIGINT  NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mcp_server (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    endpoint_url    VARCHAR(1024),
    transport_type  VARCHAR(32) NOT NULL DEFAULT 'sse',
    auth_type       VARCHAR(32) DEFAULT 'none',
    auth_config     TEXT,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    owner_id        BIGINT  NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Knowledge Graph Metadata
CREATE TABLE IF NOT EXISTS kg_graph (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    owner_id        BIGINT  NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    node_count      INT     NOT NULL DEFAULT 0,
    edge_count      INT     NOT NULL DEFAULT 0,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kg_build_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_id        BIGINT  NOT NULL,
    file_id         BIGINT,
    task_type       VARCHAR(32) NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'pending',
    progress        INT     NOT NULL DEFAULT 0,
    result          TEXT,
    error_message   TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kg_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_id        BIGINT  NOT NULL,
    node_id         VARCHAR(256) NOT NULL,
    file_id         BIGINT,
    content_snippet TEXT,
    vector_id       VARCHAR(256),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kg_node (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_id        BIGINT  NOT NULL,
    name            VARCHAR(512) NOT NULL,
    node_type       VARCHAR(64)  NOT NULL DEFAULT 'concept',
    description     TEXT,
    parent_id       BIGINT,
    properties      TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kg_edge (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_id        BIGINT  NOT NULL,
    source_node_id  BIGINT  NOT NULL,
    target_node_id  BIGINT  NOT NULL,
    edge_type       VARCHAR(64) NOT NULL DEFAULT 'RELATES_TO',
    properties      TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Competency Graph Metadata
CREATE TABLE IF NOT EXISTS comp_graph (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    owner_id        BIGINT  NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comp_assessment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT  NOT NULL,
    graph_id        BIGINT  NOT NULL,
    job_node_id     VARCHAR(256),
    result          TEXT,
    gap_analysis    TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comp_learning_path (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT  NOT NULL,
    assessment_id   BIGINT,
    path_data       TEXT NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. Security & Audit
CREATE TABLE IF NOT EXISTS sec_keyword (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word            VARCHAR(256) NOT NULL,
    category        VARCHAR(64),
    severity        VARCHAR(32) NOT NULL DEFAULT 'block',
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sec_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    rules           TEXT NOT NULL,
    target_type     VARCHAR(32),
    target_id       BIGINT,
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sec_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    session_id      VARCHAR(256),
    input_text      TEXT,
    output_text     TEXT,
    hit_rule        VARCHAR(256),
    action_taken    VARCHAR(32),
    details         TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sec_model_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT  NOT NULL,
    model_id        BIGINT  NOT NULL,
    allowed         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Model & Channel
CREATE TABLE IF NOT EXISTS model_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    alias           VARCHAR(256),
    provider        VARCHAR(64)  NOT NULL,
    model_name      VARCHAR(256) NOT NULL,
    api_key         VARCHAR(512),
    endpoint_url    VARCHAR(1024),
    capability      VARCHAR(64)  NOT NULL DEFAULT 'text',
    context_window  INT,
    max_output      INT,
    user_limit      INT,
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    is_public       BOOLEAN NOT NULL DEFAULT TRUE,
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    config          TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id        BIGINT NOT NULL,
    role_id         BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_usage_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    model_id        BIGINT  NOT NULL,
    session_id      VARCHAR(256),
    input_tokens    INT     NOT NULL DEFAULT 0,
    output_tokens   INT     NOT NULL DEFAULT 0,
    cost            DECIMAL(10,6) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channel_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(256) NOT NULL,
    channel_type    VARCHAR(64)  NOT NULL,
    config          TEXT,
    status          VARCHAR(32)  NOT NULL DEFAULT 'active',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channel_agent_binding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id      BIGINT NOT NULL,
    agent_id        BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(channel_id, agent_id)
);

-- 8. AI Chat Session
CREATE TABLE IF NOT EXISTS ai_chat_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    agent_id        VARCHAR(256),
    title           VARCHAR(512),
    last_message    TEXT,
    message_count   INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_channel_mapping (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_type    VARCHAR(64)  NOT NULL,
    channel_user_id VARCHAR(256) NOT NULL,
    platform_user_id BIGINT      NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(channel_type, channel_user_id)
);
